### ISSUE TITLE
Cannot run the extension without a server running on localhost 8080

### ISSUE THREAD

**Issue by Wadprog** [jherr/performance-extension#1]
Hi I loved your video on Brad Channel> I followed your path to create my own extension, now  I wonder how we can start the extension for production without running yarn start

**Comment by jherr** [comment]
Sorry, I didn't configure it all the way for that. You'll need to use `yarn build` but also hack a bit on the `webpack.config.js` so that the popup.html file points to the local bundle file as opposed to `http://..`. Or you could just hand edit the resulting `popup.html` file in the build directory.

I've got a bunch of other stuff I'm working on at the moment. After that I could take another look at this to do that work. Or feel free to PR it if you figure it out for yourself.
